In [1]:
!pip uninstall -y numpy
!pip install numpy==1.23.5
!pip install --upgrade sweetviz

Found existing installation: numpy 1.23.5
Uninstalling numpy-1.23.5:
  Successfully uninstalled numpy-1.23.5
  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.23.5 which is incompatible.
chex 0.1.89 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
xarray 2025.1.2 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
bigframes 1.42.0 requires numpy>=1.24.0, but you have numpy 1.23.5 which is incompatible.
albumentations 2.0.5 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
scikit-image 0.25.2 requires numpy>=1.24, but you have numpy 1.23.5 w

ERROR: Operation cancelled by user
^C


In [35]:
import pandas as pd
import sweetviz as sv

# Leer el archivo
data = pd.read_csv('/content/bank.csv')

# Generar el análisis
report = sv.analyze(data)

# Mostrar el reporte (como archivo HTML)
report.show_html('/content/reporte_sweetviz.html')


                                             |          | [  0%]   00:00 -> (? left)

Report /content/reporte_sweetviz.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [36]:
import pandas as pd

# Mostrar las primeras filas del dataset
print(data.head())

# Resumen de las columnas, tipos de datos y valores nulos
print(data.info())

# Estadísticas descriptivas de las variables numéricas
print(data.describe())

   age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 

In [37]:
# Verificar si hay valores nulos en el dataset
print(data.isnull().sum())

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64


In [38]:
# Separar la variable objetivo 'deposit' y las variables predictoras 'X'
X = data.drop('deposit', axis=1)  # Eliminar la columna 'deposit' de X
y = data['deposit']  # La columna 'deposit' es nuestra variable objetivo

# Ver los primeros valores de y
print(y.head())


0    yes
1    yes
2    yes
3    yes
4    yes
Name: deposit, dtype: object


In [39]:
# Convertir la variable objetivo 'deposit' a 0 y 1
y = y.map({'yes': 1, 'no': 0})

# Verificar que la conversión se realizó correctamente
print(y.head())


0    1
1    1
2    1
3    1
4    1
Name: deposit, dtype: int64


In [40]:
# Convertir las variables categóricas en dummy variables
X_encoded = pd.get_dummies(X)

# Verificar cómo se ve el dataset después de la codificación
print(X_encoded.head())


   age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0   59     2343    5      1042         1     -1         0        True   
1   56       45    5      1467         1     -1         0        True   
2   41     1270    5      1389         1     -1         0       False   
3   55     2476    5       579         1     -1         0       False   
4   54      184    5       673         2     -1         0        True   

   job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  month_may  \
0            False             False  ...      False      False       True   
1            False             False  ...      False      False       True   
2            False             False  ...      False      False       True   
3            False             False  ...      False      False       True   
4            False             False  ...      False      False       True   

   month_nov  month_oct  month_sep  poutcome_failure  poutcome_other  \
0      False      Fa

In [41]:
from sklearn.preprocessing import StandardScaler

# Inicializar el escalador
scaler = StandardScaler()

# Aplicar escalado solo a las columnas numéricas
num_cols = X_encoded.select_dtypes(include=['int64', 'float64']).columns
X_encoded[num_cols] = scaler.fit_transform(X_encoded[num_cols])

# Ver cómo se ve el dataset después del escalado
print(X_encoded.head())


        age   balance       day  duration  campaign     pdays  previous  \
0  1.491505  0.252525 -1.265746  1.930226 -0.554168 -0.481184  -0.36326   
1  1.239676 -0.459974 -1.265746  3.154612 -0.554168 -0.481184  -0.36326   
2 -0.019470 -0.080160 -1.265746  2.929901 -0.554168 -0.481184  -0.36326   
3  1.155733  0.293762 -1.265746  0.596366 -0.554168 -0.481184  -0.36326   
4  1.071790 -0.416876 -1.265746  0.867171 -0.186785 -0.481184  -0.36326   

   job_admin.  job_blue-collar  job_entrepreneur  ...  month_jun  month_mar  \
0        True            False             False  ...      False      False   
1        True            False             False  ...      False      False   
2       False            False             False  ...      False      False   
3       False            False             False  ...      False      False   
4        True            False             False  ...      False      False   

   month_may  month_nov  month_oct  month_sep  poutcome_failure  \
0      

In [45]:
from sklearn.model_selection import train_test_split

# Dividir los datos en entrenamiento y prueba (80% entrenamiento, 20% prueba)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# Verificar el tamaño de los conjuntos de entrenamiento y prueba
print(f'Tamaño del conjunto de entrenamiento: {X_train.shape}')
print(f'Tamaño del conjunto de prueba: {X_test.shape}')


Tamaño del conjunto de entrenamiento: (8929, 51)
Tamaño del conjunto de prueba: (2233, 51)


In [43]:
#MODELO DE REGRESIÓN LOGÍSTICA

from sklearn.linear_model import LogisticRegression

# Inicializar el modelo
model = LogisticRegression()

# Entrenar el modelo con el conjunto de entrenamiento
model.fit(X_train, y_train)

# Hacer predicciones sobre el conjunto de prueba
y_pred = model.predict(X_test)

# Ver los primeros valores de las predicciones
print(y_pred[:10])


[0 1 1 1 0 1 0 0 0 1]


In [44]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Precisión del modelo: {accuracy}')

# Mostrar el reporte de clasificación (precisión, recall, F1-score)
print('\nReporte de clasificación:\n', classification_report(y_test, y_pred))

# Mostrar la matriz de confusión
print('\nMatriz de confusión:\n', confusion_matrix(y_test, y_pred))


Precisión del modelo: 0.8083296014330497

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.81      0.83      0.82      1166
           1       0.81      0.78      0.80      1067

    accuracy                           0.81      2233
   macro avg       0.81      0.81      0.81      2233
weighted avg       0.81      0.81      0.81      2233


Matriz de confusión:
 [[972 194]
 [234 833]]


In [46]:
# Importar bibliotecas para los modelos
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [49]:
#MODELO: ÁRBOLES DE DECISIÓN

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_dt = dt_model.predict(X_test)

# Evaluar el rendimiento
print("Evaluación con Árbol de Decisión")
print("Precisión:", accuracy_score(y_test, y_pred_dt))
print("Reporte de Clasificación:\n", classification_report(y_test, y_pred_dt))
print("Matriz de Confusión:\n", confusion_matrix(y_test, y_pred_dt))


Evaluación con Árbol de Decisión
Precisión: 0.7832512315270936
Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.79      0.81      0.80      1166
           1       0.78      0.76      0.77      1067

    accuracy                           0.78      2233
   macro avg       0.78      0.78      0.78      2233
weighted avg       0.78      0.78      0.78      2233

Matriz de Confusión:
 [[939 227]
 [257 810]]


In [50]:
#MODELO: RANDOM FOREST

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_rf = rf_model.predict(X_test)

# Evaluar el rendimiento
print("Evaluación con Random Forest")
print("Precisión:", accuracy_score(y_test, y_pred_rf))
print("Reporte de Clasificación:\n", classification_report(y_test, y_pred_rf))
print("Matriz de Confusión:\n", confusion_matrix(y_test, y_pred_rf))


Evaluación con Random Forest
Precisión: 0.8410210479175997
Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.87      0.82      0.84      1166
           1       0.81      0.87      0.84      1067

    accuracy                           0.84      2233
   macro avg       0.84      0.84      0.84      2233
weighted avg       0.84      0.84      0.84      2233

Matriz de Confusión:
 [[955 211]
 [144 923]]


In [52]:
# XGBOOST

xgb_model = xgb.XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

# Hacer predicciones
y_pred_xgb = xgb_model.predict(X_test)

# Evaluar el rendimiento
print("Evaluación con XGBoost")
print("Precisión:", accuracy_score(y_test, y_pred_xgb))
print("Reporte de Clasificación:\n", classification_report(y_test, y_pred_xgb))
print("Matriz de Confusión:\n", confusion_matrix(y_test, y_pred_xgb))


Evaluación con XGBoost
Precisión: 0.8437080161218092
Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.87      0.83      0.85      1166
           1       0.82      0.86      0.84      1067

    accuracy                           0.84      2233
   macro avg       0.84      0.84      0.84      2233
weighted avg       0.84      0.84      0.84      2233

Matriz de Confusión:
 [[965 201]
 [148 919]]
